# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: abb6aafef163e3bc02a95ecc6eb30c5359de208754dbeeb56fac8bdfb623498ea5447324bd47abd41feb11d0ca92cd3ae67ff48e6b6aeb55840c78d866816bf3

test:
  secret_key_base: cbf5b4470ad76d8238d7db72064e194567179f78fb5dfc8bc3869c4e6f1a42248ec2189783a4aeb862f2ee701d06456992caec9eb058ea277bb777185bf4966b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
